port: 2424
admin_port: 2525
log:
  level: "info"
rate_limiter:
  enabled: true
  num_requests: 100
request_limits:
  max_size_bytes: 10240 # 10K
  max_num_values: 10
backend:
  type: "aerospike" # Can also be "aerospike", "azure", "cassandra", or "memcache"
  aerospike:
    host: "$AEROSPIKE_HOST"
    port: $AEROSPIKE_PORT
    namespace: "$AEROSPIKE_NAMESPACE"
  azure:
    account: "azure-account-here"
    key: "azure-key-here"
  cassandra:
    hosts: "127.0.0.1"
    keyspace: "prebid"
  memcache:
    hosts: "10.0.0.1:11211" # Can also use an array for multiple hosts
compression:
  type: "snappy" # Can also be "none"
metrics:
  type: "none" # Can also be "influx"
  influx:
    host: "http://influx.prebid.com"
    database: "some-database"
    username: "influx-username"
    password: "influx-password"
stats:
  host: "$STATS_HOST"
  port: "$STATS_PORT"
  dc_name: "$STATS_DC_NAME"
server:
  port: "$SERVER_PORT"
  name: "$SERVER_NAME"