name: Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  Package:
    name: Package and Publish Docker Image
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:

    - name: Get Version
        id: get_version
        run: |
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\/}
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v}
  
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker build --build-arg DEPLOY_VERSION=${{ steps.get_version.outputs.version }} -t docker.io/mansinahar/prebid-server:${{ steps.get_version.outputs.version }} .

    - name: Login to Dockerhub
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Publish to Dockerhub
      run: |
        docker push docker.io/mansinahar/prebid-server:${{ steps.get_version.outputs.version }}

    - name: Logout of Dockerhub
      run: |
        docker logout docker.io