name: Release

on:
  workflow_dispatch

jobs:
  check-permission:
    name: Check permission
    if: contains(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check user permission
        uses: actions-cool/check-user-permission@v2.2.0
        id: check
        with:
          require: 'write'
    outputs:
      hasWritePermission: ${{ steps.check.outputs.require-result }}

  release:
    name: Create Release
    needs: check-permission
    if: contains(needs.check-permission.outputs.hasWritePermission, 'true')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: get_version
        run: |
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\/}
      - name: Create & Publish Release
        uses: release-drafter/release-drafter@v5.12.1
        with:
          name: ${{ steps.get_version.outputs.tag }}
          tag: ${{ steps.get_version.outputs.tag }}
          version: ${{ steps.get_version.outputs.tag }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}